---

- name: install required packages
  apt:
    name: "{{ packages }}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - "php{{ php_version }}"
    - "php{{ php_version }}-cli"
    - apache2
    - "libapache2-mod-php{{ php_version }}"

- name: install additional packages
  apt:
    name: "{{ php_additional_packages }}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600

- name: update php.ini
  lineinfile:
    path: "/etc/php/{{ php_version }}/apache2/php.ini"
    regexp: "^{{ item.key }} = "
    line: "{{ item.key }} = {{ item.value }}"
  with_items: "{{ php_ini_settings }}"

- name: update php.ini
  lineinfile:
    path: "/etc/php/{{ php_version }}/cli/php.ini"
    regexp: "^{{ item.key }} = "
    line: "{{ item.key }} = {{ item.value }}"
  with_items: "{{ php_ini_settings }}"

- name: enable additional modules
  apache2_module:
    state: "{{ item.state }}"
    name: "{{ item.name }}"
  with_items: "{{ apache_additional_modules }}"

- name: Remove default vhost in sites-enabled.
  file:
    path: "/etc/apache2/sites-enabled/000-default.conf"
    state: absent
  notify: restart apache
  when: apache_remove_default_vhost

...
