---

- name: install required packages
  apt:
    pkg: "{{ item }}"
    state: latest
    allow_unauthenticated: yes
    autoclean: yes
    autoremove: yes
  with_items:
  - "php{{ php_version }}"
  - "php{{ php_version }}-cli"
  - apache2
  - "libapache2-mod-php{{ php_version }}"

- name: update php.ini
  lineinfile:
    path: "/etc/php/{{ php_version }}/apache2/php.ini"
    regexp: "^{{ item.key }} = "
    line: "{{ item.key }} = {{ item.value }}"
  with_items: "{{ php_ini_settings }}"

- name: update php.ini
  lineinfile:
    path: "/etc/php/{{ php_version }}/cli/php.ini"
    regexp: "^{{ item.key }} = "
    line: "{{ item.key }} = {{ item.value }}"
  with_items: "{{ php_ini_settings }}"

...
