---
- hosts: all
  become: true
  become_method: sudo

  vars:
    apache_php_version: 8.2
    apache_php_ini_settings:
    - key: post_max_size
      value: 512M
    - key: upload_max_filesize
      value: 512M
    - key: max_execution_time
      value: 600
    - key: max_input_time
      value: 600
    sury_php_packages:
    - php8.2-gd
    - php8.2-mysql
    - php8.2-curl
    - php8.2-mcrypt
    - php8.2-tidy
    - php8.2-zip
    - php-imagick
    - php-geoip
    - geoip-bin
    apache_php_additional_modules:
    - name: rewrite
      state: present
    apache_php_remove_default_vhost: true

  roles:
  - andrelohmann.root_colored_prompt
  - ansible-role-apache_php
...
