---
- name: Converge
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  vars:
    sury_php_packages:
    - php8.3
    - php8.3-cli
    - php8.3-gd
    - php8.3-mysql
    - php8.3-curl
    - php8.3-tidy
    - php8.3-zip
    apache_php_version: 8.3
    apache_php_ini_settings:
    - key: post_max_size
      value: 512M
    - key: upload_max_filesize
      value: 512M
    - key: max_execution_time
      value: 600
    - key: max_input_time
      value: 600
    apache_php_additional_modules:
    - name: rewrite
      state: present
    apache_php_remove_default_vhost: true
  roles:
  - role: andrelohmann.sury_php
  tasks:
  - name: Include andrelohmann.apache_php
    ansible.builtin.include_role:
      name: "andrelohmann.apache_php"
...
